version: '3'
services:
  app:
    image: hw3
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - .:/assign2
